[package]
name = "mikrodb"
version = "0.1.0"
authors = ["mikit <mikihito0906@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = "1.0.92"
serde_json = "1.0.39"
serde_derive = "1.0.92"
byteorder = "1.3.2"
sha2 = "0.8.0"
